// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dltmtjaqxiwoqefnvohn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsdG10amFxeGl3b3FlZm52b2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDgyMDYsImV4cCI6MjA3MTg4NDIwNn0.AaOAkleRn2FmqHnuZ7OkW-Wo8CNaXN-5qfsTegUecuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});